<?php
define( 'BASE_DIR_ADMIN', 'brigloo' );
require_once $_SERVER['DOCUMENT_ROOT']. '/' . BASE_DIR_ADMIN . '/config/config.php';

define( 'ADMIN_VIEW_DIR', 'views' );
define( 'ADMIN_JS_DIR', 'js' );
define( 'ADMIN_PLUGINS_DIR', 'plugins' );

define( 'ADMIN_CSS_PATH', BASE_URL . DIR_SEPERATOR . BACKEND_DIR . DIR_SEPERATOR . ASSET_DIR . DIR_SEPERATOR . 'css' . DIR_SEPERATOR );
define( 'ADMIN_JS_PLUGINS_PATH', BASE_URL . DIR_SEPERATOR . BACKEND_DIR . DIR_SEPERATOR . ASSET_DIR . DIR_SEPERATOR . ADMIN_JS_DIR . DIR_SEPERATOR . ADMIN_PLUGINS_DIR . DIR_SEPERATOR );

/* Views File */
define( 'VW_ADMIN_HOME', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'home.php' );
define( 'VW_ADMIN_USER_LIST', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'user_list.php' );
define( 'VW_ADMIN_GROUP_LIST', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'group_list.php' );
define( 'VW_ADMIN_PICK_LIST', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'pickup_list.php' );
define( 'VW_ADMIN_DRIVER_PICKUP_AMT', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'driver_pickup_amt.php' );
define( 'VW_ADMIN_GENERAL_SETTING', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'general_setting.php' );
define( 'VW_ADMIN_ACTIVITY_LOG', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'activity_logs.php' );
define( 'VW_ADMIN_REPORT', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'admin_report.php' );
define( 'VW_ADMIN_INTERRUPT_JOB', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'interrupt_jobs.php' );
define( 'VW_ADMIN_DRIVER_LIST', BASE_URL . BACKEND_DIR . DIR_SEPERATOR . ADMIN_VIEW_DIR . DIR_SEPERATOR . 'driver_list_report.php' );


